# Generated by Django 5.1.4 on 2025-02-11 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_walletconnection_analysis_wa_ip_addr_b39875_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
